name:                pianoreps
version:             0.1.0.0
github:              "mitchellvitez/pianoreps"
author:              "Mitchell Vitez"
maintainer:          "mitchell@vitez.me"
copyright:           "2020"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/mitchellvitez/pianoreps#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- monad-logger
- mtl
- persistent
- persistent-sqlite
- persistent-template
- rando
- random
- resource-pool
- say
- servant-server
- sqlite-simple
- text
- transformers
- wai
- warp
- yesod-core

library:
  source-dirs: src

executables:
  pianoreps-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
